### ISSUE TITLE
ModuleNotFound

### ISSUE THREAD

**Issue by przkop** [juanmanzanero/fastest-lap#41]
Can you please explain and help me solve this?

import sys,os,inspect
sys.path.append("/C:/Users/Przemek/Desktop/fastest-lap/examples/python")
import fastest_lap
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    import fastest_lap
ModuleNotFoundError: No module named 'fastest_lap'

**Comment by juanmanzanero** [comment]
I think in Windows you shall use double backslash in paths. Also. you must point to the `include` directory as mentioned in the documentation: 
```python
sys.path.append("C:\\Users\\Przemek\\Desktop\\fastest-lap\\include")
```

I encourage you to learn some python before using this library, otherwise you will be super limited! Surely after a 2h youtube lesson or similar you will have a lot of extra knowledge to tame these errors.
